apiVersion: apps/v1
kind: Deployment

metadata:
  name: fairshare-server
  namespace: nonprod

spec:
  replicas: 2

  selector:
    matchLabels:
      app: fairshare-server

  template:
    metadata:
      labels:
        app: fairshare-server

    spec:
      containers:
        - name: fairshare-server
          image: ghcr.io/taku10/fairshare-server:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: NODE_ENV
              value: "nonprod"

            - name: PORT
              value: "5000"

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: fairshare-secrets
                  key: MONGO_URI