apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: fairshare
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Taku10/k3s-clusters.git
    targetRevision: main
    path: apps/fairshare

  destination:
    server: https://kubernetes.default.svc
    namespace: nonprod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true